name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@V27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - run: nix flake check

      # Verify the update script WORKS but we don't actually commit anything
      # in the test job.
      - run: ./update.py